# Generated by Django 5.1.5 on 2025-01-22 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_chat_room_remove_chat_user_customuser_message_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', 'receiver', 'timestamp'], name='app_message_sender__b80c2e_idx'),
        ),
    ]
